version: 3
includes:
  main:
    taskfile: ../Taskfile.yml
    flatten: true
env:
  SOLO_NETWORK_SIZE: 5
  SOLO_NAMESPACE: solo-jeromy-20241231
  SOLO_CHART_VERSION: 0.36.1
  CONSENSUS_NODE_VERSION: v0.57.2
  VALUES_FLAG: "--values-file init-containers-values.yaml"
  SETTINGS_FLAG: "--settings-txt settings.txt"
  SOLO_HOME: "/Users/user/.solo-{{.SOLO_NAMESPACE}}"
  # LOG4J2_FLAG: "--log4j2-xml log4j2.xml"
  # APPLICATION_PROPERTIES_FLAG: "--application-properties application.properties"
  # HEDERA_SERVICES_ROOT: "/Users/user/source/hedera-services"
  # LOCAL_BUILD_FLAG: "--local-build \"{{.HEDERA_SERVICES_ROOT}}/hedera-node/data\""
